# Application
app.service-name=${SERVICE_NAME:card-management}
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8080}

# Spring Boot
spring.threads.virtual.enabled=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.jakarta.persistence.lock.timeout=5000

# Flyway
spring.flyway.clean-disabled=true
spring.flyway.clean-on-validation-error=false
spring.jpa.flyway.enabled=true
spring.flyway.out-of-order=true
spring.flyway.baseline-on-migrate=true

# Logging
logging.level.com.processing=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=card-management
management.metrics.distribution.percentiles-histogram.[http.server.requests]=true
management.metrics.distribution.percentiles.[http.server.requests]=0.5,0.95,0.99

# Metrics Scheduler
app.metrics.scheduler.enabled=${METRICS_SCHEDULER_ENABLED:true}
app.metrics.scheduler.update-rate-ms=${METRICS_SHEDULER_UPDATE_RATE_MS:5000}

# Card Service
app.card-service.card-validity-period=${CARD_VALIDITY_PERIOD:3}
app.card-service.max-page-limit=${MAX_PAGE_LIMIT:10000}
app.card-service.max-card-creation-retries=${MAX_CARD_CREATION_RETRIES:3}

# Card Service Defaults
app.card-service.defaults.page-offset=${DEFAULT_PAGE_OFFSET:0}
app.card-service.defaults.page-limit=${DEFAULT_PAGE_LIMIT:50}
app.card-service.defaults.currency-code=${DEFAULT_CURRENCY_CODE:643}
app.card-service.defaults.daily-limit=${DEFAULT_DAILY_LIMIT:15000000}
app.card-service.defaults.monthly-limit=${DEFAULT_MONTHLY_LIMIT:300000000}
app.card-service.defaults.balance=${DEFAULT_BALANCE:100000000}

# Generator
app.card-generator.min-balance=${GENERATOR_MIN_BALANCE:1000000}
app.card-generator.max-balance=${GENERATOR_MAX_BALANCE:50000000}
app.card-generator.min-daily-limit=${GENERATOR_MIN_DAILY_LIMIT:5000000}
app.card-generator.max-daily-limit=${GENERATOR_MAX_DAILY_LIMIT:30000000}
app.card-generator.currency-code=${GENERATOR_CURRENCY_CODE:643}
app.card-generator.max-count=${GENERATOR_MAX_COUNT:10000}

# Testing
app.card-service.tests.load.max-parallel-requests=${LOAD_TESTS_MAX_PARALLEL_REQUESTS:50}
app.card-service.tests.load.max-total-requests=${LOAD_TESTS_MAX_TOTAL_REQUESTS:5000}

# Outbox
app.outbox.interval-ms=${OUTBOX_INTERVAL_MS:1000}
app.outbox.max-retry-count=${OUTBOX_MAX_RETRY_COUNT:3}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:smp}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:smp}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
